#!/bin/sh /etc/rc.common

USE_PROCD=1
START=90

PROG=/usr/bin/sing-box-sub
CONFIG=/etc/config/sing-box-sub

start_service() {
    local listen_addr

    config_load sing-box-sub
    config_get listen_addr settings listen_addr "0.0.0.0:40533"

    procd_open_instance
    procd_set_param command "$PROG" -d
    procd_set_param env LISTEN_ADDR="$listen_addr"
    procd_set_param file "$CONFIG"
    procd_set_param respawn
    procd_close_instance
}

service_triggers() {
    procd_add_reload_trigger sing-box-sub
}
